// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bakzzkadgmyvvvnpuvki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJha3p6a2FkZ215dnZ2bnB1dmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0MTczMjksImV4cCI6MjA4MTk5MzMyOX0._tdT8u-ApjOACB1KVWg3honn-egJKfqTZWSKCW2goCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});